name: WhaleTrucker Health Check
on: [push, pull_request]

jobs:
  audit-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run Audit
        run: |
          brew tap scutuatua-crypto/homebrew-whaletrucker
          brew audit --strict scutua-mcp
